title: My Blog
author: Eric Xue
email: eric.xy.xue@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog

# social links
github_username:  s-erxue # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
